name: reuse
on: 
  workflow_call:
    inputs:
      artifact_name:
        description: name of the artifact to be downloaded
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: result of the reusable workflow
        value: ${{jobs.deploy.outputs.outcome}}
      
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.output_info.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: output information
        id: output_info
        run: echo "::set-output name=step-result::success"